---
title: "QA_that_introduction: How the package works "
author: "George Papadopoulos"
date: "21/09/2021"
output: html_document
---



## Introduction 


The obvious inspiration comes from the `test_that` package in R that in turn was inspirted from test practices applied in C#, Java, Python etc. Many thanks to all the developers.

**Things may change as development progresses so do keep in mind that.**


The concept here is to include `tests` that are combined into a `checks` that are in turn collected into `sesctions` for each area/code we want to QA.


More specifically, the collection here wil aim at including the following:

+ The basic element, the atom of QA will be the `test`:
    + `test_equal`
    + `test_identical`
    + `test_match`
    + `test_numeric`
    + `test_character`
    + `test_true`
    + `test_false`
    + `test_NA`
    + any other that may arise in the future
+ The `tests` will be combined into `checks` as follows:
    + `check_that("text description", {test_equal(...), test_identical(...). ...}  )`
    + output will be a sumam ry of the whole process
    + see if warnings can be caught there as well
    + Other items to be added in the future
+ Tests will be combined into `QA_that_` sections regarding spcecific areas  i want to QA
    + `QA_that_`(s) are files containing all checks that need to be conducted in the project. The corresponding filenames will need to start with
    `QA_that_` so as to distinguish them from anything else and also they need to be included in a `QA_that` folder
    + `QA_that_`(s) can be fore example tests that need to be conducted in A or B tables in PRSQ
    + For better structure all files should start with `QA_that_` prefix so as to be able to collect results better


More to be aded as we go along in time


### Thisngs to remember:

+ QA files should start with `QA_that_` so that they make sense and also to enbable the system to pick them up esier. For examnple `QA_that_A_tables_are_in_line_with_B.R`
+ a number of global variables are crated to keep track of things. You wont need to worry about that when coding tests - Discontinued
+ all QA should be in one folder and the starting point is considered the root directory of your project
+ IMPORTANT: the function `use_QA()` needs to be run from your console  in the root directory - otherwise the folders will be created in the folder where the function resides!
+ to add more as needed


### QA logs and other elements

The process will create a corresponding QA log to contain and summarise all the tests conducted in your code and tables. The output of the functions are neatly contained in a list dataframes so that further analysis can be added as needed.







